### ISSUE TITLE
Create ReadMe for repository

### ISSUE THREAD

**Issue by Tania435** [linz/basemaps#1]
### User Story

In order to have a repository that complies with contributing guidelines as a Basemaps Developer I want a detailed Read Me for the repository 
(optional: instead of [existing behaviour]).

#### Acceptance Criteria
- [x] Contain the license
- [ ] Features, components, database
- [x] Introduction to the project
- [x]  Use buildings repo readme as a good example template https://github.com/linz/nz-buildings/blob/master/README.rst

**Add an _Assignee_, _Milestone_, _Release_ and any relevant _Labels_.**

**Comment by IReese** [comment]
I started in on this issue today.  Anyone please feel free to correct what I get wrong

**Comment by blacha** [comment]
We have not decided on the features, components, database etc.. so I don't think we can add that to the readme just yet, I have made a PR with a very concise readme on the stuff that has been decided.

we should update the readme as we add functionality
