### ISSUE TITLE
Header & footer styling issues on Safari

### ISSUE THREAD

**Issue by wayne-shih** [linz/basemaps#1133]
### Bug Description
Header and footer components breaking on Safari (see screenshots below) 
Chrome & Firefox looks as intended. 

#### Steps to Reproduce
1. Go to 'https://basemaps.linz.govt.nz/'
2. See error

#### Desktop
 - Environment: macOS 11.0 Big Sur Beta (20A5354i)
 - Relevant Software Versions: Safari Version 14.0 (16610.1.25.1.3)

Also tested on macOS Catalina 10.15.6 [latest public build] & Safari Version 14.0 (15610.1.23, 15610) same issue. 

#### Screenshots
Safari — 
<img width="1440" src="https://user-images.githubusercontent.com/51947763/92045087-cd82b880-edd3-11ea-9fd3-ee8bb629e58d.png">

Chrome — 
<img width="1440" src="https://user-images.githubusercontent.com/51947763/92045096-d2476c80-edd3-11ea-9c5d-d9bee172def8.png">

**Add an _Assignee_, _Milestone_, _Release_ and any relevant _Labels_.**

**Comment by palmerj** [comment]
I don't get the issue with version 13.1.2 (15609.3.5.1.3) running on Catalina 10.15.6. See

<img width="1526" alt="basemaps-safari_13 1 2" src="https://user-images.githubusercontent.com/580022/92048218-7b896500-edca-11ea-90c0-ea3ad0c0bc70.png">

I think 14.0 is a beta release of Safari.

**Comment by wayne-shih** [comment]
Huh, you're right! Back installed to Version 13.1.2 (13609.3.5.1.5) and it's rendering as your screenshot. Must be a Safari 14 β issue then. 🙃 Footer still looks different compared to Chrome&Firefox tho. (feel free to close this if it's a wontfix; it was mainly the header that was bugging me)

**Comment by palmerj** [comment]
Ah yeah you are right the footer definitely needs to be fixed.

**Comment by knockerdesign** [comment]
So what I'm seeing in Safari 13 is a slightly broken header and fat footer. It's fine on Safari when I view the header and footer in Storybook:  https://linz.github.io/Lui/?path=/story/lui-html-design-system--lui-header-footer

The big difference is Storybook has the SVG logo's as a linked file in an img tag. 
![image](https://user-images.githubusercontent.com/3282899/92065818-76411000-edf4-11ea-9d56-6580b9026450.png)

Basemaps has the SVG's inline, and the viewbox for the SVG's is pretty big! Not sure how the CSS would influence the inline width's/ heights... that's what's probably messing with the layout

**Comment by knockerdesign** [comment]
So what I'm seeing in Safari 13 is a slightly broken header and fat footer. It's fine on Safari when I view the header and footer in Storybook:  https://linz.github.io/Lui/?path=/story/lui-html-design-system--lui-header-footer

The big difference is Storybook has the SVG logo's as a linked file in an img tag. 
![image](https://user-images.githubusercontent.com/3282899/92065818-76411000-edf4-11ea-9d56-6580b9026450.png)

Basemaps has the SVG's inline, and the viewbox for the SVG's is pretty big! Not sure how the CSS would influence the inline width's/ heights... that's what's probably messing with the layout

**Comment by jacott** [comment]
@wayne-shih Are you able to check if the header is also fixed in Safari 14 (technology preview)?

**Comment by wayne-shih** [comment]
Whoop whoop! Looks great on 14.0, thanks guys 😄 🎉 

<img width="1399" alt="Screen Shot 2020-09-07 at 1 09 56 PM" src="https://user-images.githubusercontent.com/51947763/92339674-73536180-f10b-11ea-8e53-77e1007cb8a4.png">
