### ISSUE TITLE
Imagery Layering

### ISSUE THREAD

**Issue by charlottedawson** [linz/basemaps#13]
### User Story

In order to have a complete Basemap dataset as a Doug(persona) I want to be able to transition between imagery datasets in QGIS .

#### Acceptance Criteria
- [x] merge Datasets together
- [x] zoom scale
- [x] definition of rule system (image metadata/layer priority)
- [x] Sentinal to Gisborne Rural Imagery
- [x] Rural needs to be COG'd
- [x] Needs to work in QGIS

**Comment by josephramsay** [comment]
Attach and dissolve bboxes into superpoly
![dissolve](https://user-images.githubusercontent.com/1757695/70474487-937fd100-1b37-11ea-87ac-010155b8c8c2.gif)

**Comment by josephramsay** [comment]
Basic tile cover over superpolys
![cover_12](https://user-images.githubusercontent.com/1757695/70474583-c0cc7f00-1b37-11ea-8d05-3e91ad1ea749.gif)

**Comment by josephramsay** [comment]
Percent coverage tile selection 10%,25%,50%,75%
![zoomByArea](https://user-images.githubusercontent.com/1757695/70474756-0ab56500-1b38-11ea-8881-227bebf570ea.gif)

**Comment by blacha** [comment]
This is all done.
