### ISSUE TITLE
Add Bathy COGs

### ISSUE THREAD

**Issue by charlottedawson** [linz/basemaps#192]
### User Story

In order to have a visually appealing basemap as a user  I want some bathymetry.

@JBLINZ TO UPDATE ISSUE

#### Acceptance Criteria
- [x] Bathy COG
- [x] GebCo bathy cog added to Basemap Dev
- [ ] ...

**Comment by IReese** [comment]
@blacha Thinb drive delivered to your desk.

Files are:
NIWA_Bathy
GEBCO_Bathy

**Comment by IReese** [comment]
Investigating "lines" appearing near the poles
AND
clipping GEBCO to webmercator bounds

**Comment by blacha** [comment]
Attaching example of lines inside of bathy file for reference.
![Uploading 2019-12BathyLines.png…]()

**Comment by IReese** [comment]
Clipped GEBCO delivered

**Comment by charlottedawson** [comment]
Issse #71 (Basemaps Team) refers to the Lines Bug shown above.

**Comment by blacha** [comment]
Bathy has been added!

![Screenshot from 2019-12-18 13-48-18.png](https://images.zenhubusercontent.com/5d2ba25ca9a8190134da519b/07ff15c7-e66b-44ba-8d86-307bee68c83b)
