### ISSUE TITLE
linz/basemaps lint error on docker build

### ISSUE THREAD

**Issue by AllenSuttonValocity** [linz/basemaps#1985]
### Bug Description
When executing docker build -t basemap Dockerfile I get an error with eslint

#### Steps to Reproduce
Execute docker build command

#### Desktop
 - Environment: Windows

#### Screenshots
![image](https://user-images.githubusercontent.com/57972301/143333157-1f1f7d86-c14b-4478-ab8d-839f487f2125.png)

**Comment by blacha** [comment]
Ahh the docker container, use to be our CI pipeline we have since moved across to github actions for our CI.

I have made a PR that will switch the docker container to just building the system.

**Comment by AllenSuttonValocity** [comment]
Thanks for the prompt response.

Regards,
Allen

**Comment by AllenSuttonValocity** [comment]
Unfortunately using the changes to Dockerfile in the pull request, the Docker build command still fails on yarn run lint

![image](https://user-images.githubusercontent.com/57972301/143340657-c7aeb87b-166b-4b74-93a5-a654a66ceae8.png)
