### ISSUE TITLE
Correct Imagery errors

### ISSUE THREAD

**Issue by richfone** [linz/basemaps#260]
### User Story

In order to [accomplish goal] as a [role] I want [capability] 
(optional: instead of [existing behaviour]).

#### Acceptance Criteria
- [ ] ...
- [ ] ...
- [ ] ...

**Add an _Assignee_, _Milestone_, _Release_ and any relevant _Labels_.**

**Comment by josephramsay** [comment]
Comparison between resampling methods in COG generation [nearest, mode, lanczos, average, bilinear, cubic, cubicspline]
![wlg-urb](https://user-images.githubusercontent.com/1757695/75406971-be2f3800-5976-11ea-808a-1d8711c06829.gif)

**Comment by JBLINZ** [comment]
@josephramsay Can you post the original unalter image too?

**Comment by josephramsay** [comment]
Fix tested and merged, batch running against s3 as final test
