### ISSUE TITLE
Add to geopandas.xyz-services

### ISSUE THREAD

**Issue by billgeo** [linz/basemaps#3015]
### User Story

Might be useful for Geopandas users to have LINZ services pre-configured here: https://github.com/geopandas/xyzservices/issues/153

#### Acceptance Criteria

- [ ] ...
- [ ] ...
- [ ] ...

**Add an _Assignee_, _Milestone_, _Release_ and any relevant _Labels_.**

**Comment by dwsilk** [comment]
Happy for anyone who needs this to go ahead and add it! No action required on this repo.
