### ISSUE TITLE
Missing parks in topo data/styling

### ISSUE THREAD

**Issue by antonmarsden** [linz/basemaps#3318]
### Bug Description

Seeing white space where parks should be. Is this data/styling omitted deliberately?

#### Steps to Reproduce

Look at the topo map (see screenshot). You can visually validate that the white space is actually a park by either:
a) checking against the aerial imagery
b) going for a short walk from the LINZ Wgtn office

#### Desktop

- Chrome, Windows

#### Screenshots

![image](https://github.com/user-attachments/assets/fba765cf-6a86-484a-b95c-26b9bd8a3aa5)

**Add an _Assignee_, _Milestone_, _Release_ and any relevant _Labels_.**

**Comment by dwsilk** [comment]
Hi Anton

Toitū Te Whenua LINZ has never mapped minor cricket ovals or croquet greens or other forms of urban park. There is a sports field layer in the Topo50 Map Series but it's only used for a few major sports fields - the Basin Reserve is the only cricket oval we've mapped in all of Wellington. We do map native and exotic forests, which accounts for the other green areas in the screenshot above.

I guess it is also a styling omission in the sense that some other basemaps use a shade of green as the default for all non-built environments. Our Topographic style was created to closely align with the Topo50 Map Series cartography which displays all grass/pasture areas in white. This styling could be changed by the user of the vector tile service.

**Comment by antonmarsden** [comment]
@dwsilk Great, thanks for explaining this. Good to understand what the Topo50 conventions are. As an aside, it's interesting to compare and contrast the LINZ topo and OpenStreetMap. The LINZ map generally has the best vegetation detail overall, but OSM contains abundant feature information.

**Comment by dwsilk** [comment]
There are millions of features in OpenStreetMap that were sourced from Toitū Te Whenua LINZ along with semi-automated data update processes that continue weekly, particularly for features like roads, addresses and building outlines. OpenStreetMap community contributors have then added a large amount of place-of-interest data that we do not have.

Unfortunately our licenses are incompatible. We've signed a waiver that allows OSM to import our data, but we cannot import theirs without requiring more restrictions to how our mapping data can be used, which is unfortunate.
